org.gradle.jvmargs=-Xmx1G
minecraft_version=26.1.2
loader_version=0.19.3
quilt_loader_version=0.31.0-beta.4
neoforge_version=26.1.2.109
moddev_version=2.0.147
forgified_fabric_api_version=0.155.2+26.1.2+3.5.5
loom_version=1.16-SNAPSHOT
mod_version=1.0-SNAPSHOT
maven_group=com.meekdev
archives_base_name=amnetic
fabric_version=0.150.0+26.1.2
imguimc_version=2.0.5
iris_fabric_version=1.11.4+26.1-fabric
iris_neoforge_version=1.11.4+26.1-neoforge
sodium_fabric_version=mc26.1.2-0.9.2-fabric
sodium_neoforge_version=mc26.1.2-0.9.2-neoforge

lwjgl_version=3.4.1
