package com.meekdev.amnetic.client.light;

import com.meekdev.amnetic.client.render.ShaderProgram;
import net.minecraft.resources.Identifier;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

public final class LightStyles {

    public static final Identifier HOOK =
            Identifier.fromNamespaceAndPath("amnetic", "shaders/light/styles.glsl");

    private static final Map<String, Integer> BY_NAME = new LinkedHashMap<>();
    private static final List<String> BODIES = new ArrayList<>();

    static {
        ShaderProgram.registerVirtualSource(HOOK, LightStyles::source);
    }

    private LightStyles() {
    }

    public static void touch() {
    }

    public static synchronized int register(String name, String glslBody) {
        Integer existing = BY_NAME.get(name);
        if (existing != null) {
            BODIES.set(existing - 1, glslBody);
        } else {
            BODIES.add(glslBody);
            existing = BODIES.size();
            BY_NAME.put(name, existing);
        }
        ShaderProgram.invalidateAll();
        return existing;
    }

    public static synchronized Integer id(String name) {
        return BY_NAME.get(name);
    }

    public static synchronized void clear() {
        BY_NAME.clear();
        BODIES.clear();
        ShaderProgram.invalidateAll();
    }

    private static synchronized String source() {
        StringBuilder out = new StringBuilder();
        out.append("// generated by amnetic LightStyles\n");
        out.append("#define AMNETIC_STYLE_POINT 0\n");
        out.append("#define AMNETIC_STYLE_SHADE 1\n");
        out.append("void amneticLightStyle(int style, int stage, inout vec3 p, ")
                .append("inout float atten, inout vec3 color, vec3 lightPos, vec3 lightDir) {\n");
        for (int i = 0; i < BODIES.size(); i++) {
            out.append(i == 0 ? "    if (style == " : "    else if (style == ")
                    .append(i + 1).append(") {\n")
                    .append(BODIES.get(i)).append("\n    }\n");
        }
        // the parameters go unread when nothing is registered, and some drivers warn on that
        out.append("    p = p; atten = atten; color = color;\n}\n");
        return out.toString();
    }
}
