plugins {
    id 'net.fabricmc.fabric-loom' version '1.16.3'
}

version = project.mod_version + "-examples"
group = "com.example"

base {
    archivesName = "amnetic-examples"
}

repositories {
    exclusiveContent {
        forRepository {
            maven {
                url = "https://maven.ryanhcode.dev/releases"
                name = "RyanHCode Maven"
            }
        }
        filter {
            includeGroup("foundry.imguimc")
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    implementation project(':26.1.2')

    localRuntime "foundry.imguimc:imguimc-fabric-26.1:${project.imguimc_version}"
}

loom {
    mods {
        "amnetic-examples" {
            sourceSet sourceSets.main
        }
        // load the Amnetic lib as a mod in the examples dev run (the examples mod depends on it)
        "amnetic" {
            sourceSet project(":26.1.2").sourceSets.main
        }
    }
}

processResources {
    inputs.property "version", project.version
    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

def targetJavaVersion = 25
tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        it.options.release.set(targetJavaVersion)
    }
}

java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
}
