modLoader="javafml"
loaderVersion="[1,)"
license="All-Rights-Reserved"

[[mixins]]
config="amnetic.mixins.json"

[[mods]]
modId="amnetic"
version="${version}"
displayName="Amnetic"
description='''Rendering utility library for Minecraft.'''

[[dependencies.amnetic]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="CLIENT"

[[dependencies.amnetic]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version}]"
ordering="NONE"
side="CLIENT"

[[dependencies.amnetic]]
modId="fabric_api"
type="required"
versionRange="*"
ordering="NONE"
side="CLIENT"

[[dependencies.amnetic]]
modId="imguimc"
type="optional"
versionRange="[${imguimc_version},)"
ordering="AFTER"
side="CLIENT"

[[dependencies.amnetic]]
modId="iris"
type="optional"
versionRange="[1.11.4,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.amnetic]]
modId="sodium"
type="optional"
versionRange="[0.9.2,)"
ordering="AFTER"
side="CLIENT"
